### ISSUE TITLE
uValue is undefined

### ISSUE THREAD

**Issue by ahume** [launchdarkly/node-client#51]
Running 3.0.6. With ld_relay and Redis.

```
/Users/ahume/work/flags/node_modules/ldclient-node/evaluate_flag.js:168
  if (Array === uValue.constructor) {
                      ^

TypeError: Cannot read property 'constructor' of undefined
    at clause_match_user (/Users/ahume/work/flags/node_modules/ldclient-node/evaluate_flag.js:168:23)
    at rule_match_user (/Users/ahume/work/flags/node_modules/ldclient-node/evaluate_flag.js:146:10)
    at evalRules (/Users/ahume/work/flags/node_modules/ldclient-node/evaluate_flag.js:125:9)
    at /Users/ahume/work/flags/node_modules/ldclient-node/evaluate_flag.js:89:9
    at /Users/ahume/work/flags/node_modules/ldclient-node/node_modules/async/dist/async.js:1013:9
    at /Users/ahume/work/flags/node_modules/ldclient-node/node_modules/async/dist/async.js:356:16
    at replenish (/Users/ahume/work/flags/node_modules/ldclient-node/node_modules/async/dist/async.js:877:25)
    at /Users/ahume/work/flags/node_modules/ldclient-node/node_modules/async/dist/async.js:886:9
    at _asyncMap (/Users/ahume/work/flags/node_modules/ldclient-node/node_modules/async/dist/async.js:1006:5)
    at /Users/ahume/work/flags/node_modules/ldclient-node/node_modules/async/dist/async.js:1092:16
kyloren:flags ahume$ node src/server.js
info: flags:app-server http://localhost:3000
```

`uValue` seems to be undefined. Blunt fix is to check for this, so changing line 160.

`if (uValue === null) {`
to
`if (uValue === null || uValue === undefined) {`

**Comment by ahume** [comment]
My fault. Sorry. Although might be worth doing something here when unexpected data is passed in.
